language: ruby
services:
  - mysql
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
gemfile:
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
env:
  - DB=mysql
  - DB=sqlite
matrix:
  exclude:
   - rvm: "2.0"
     gemfile: gemfiles/activerecord_5.0.gemfile
   - rvm: "2.0"
     gemfile: gemfiles/activerecord_5.1.gemfile
   - rvm: "2.1"
     gemfile: gemfiles/activerecord_5.0.gemfile
   - rvm: "2.1"
     gemfile: gemfiles/activerecord_5.1.gemfile
before_script:
  - "cp spec/{.travis.,}database.yml"
  - "bundle exec rake db:prepare"
script: bundle exec rake spec
sudo: false
